language: dart
dart:
  # Install the latest stable release
  - stable

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - pub build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    recipients:
      - luke.chi@gmail.com
    on_success: always
    on_failure: always
